package.json
src/App.tsx
src/components/CollateralChoices.tsx
src/components/NetworkDropdown.tsx
src/config.ts
src/store/app.ts
src/store/vaults.ts
src/util.ts
src/views/ErrorPage.tsx
src/views/Vaults.tsx
yarn.lock

refs https://github.com/Agoric/dapp-inter/issues/1
For now it just queries vstorage for all the vault manager keys, e.g. `published.vaultFactory.manager0`, from there we can read their metrics and governed params etc.
Uses `react-query` to query vstorage, since `casting` only supports querying data not keys.

View collateral choices

---

src/components/CollateralChoice.tsx
src/components/NewVault.tsx
src/service/vaults.ts
src/store/vaults.ts
src/utils/displayFunctions.ts

Also added a button that will eventually be used to test sending an loan offer.

fix: update price feed data format

---

package.json
src/App.tsx
src/components/CollateralChoice.tsx
src/components/ConnectWalletButton.tsx
src/components/OfferSignerBridge.tsx
src/components/SmartWalletNotFoundToast.tsx
src/components/WalletBridge.tsx
src/config.ts
src/service/wallet.ts
src/store/app.ts
src/vite-env.d.ts
yarn.lock

refs #4 
refs #9
refs #11 
[Blocked] https://github.com/Agoric/dapp-inter/pull/28/commits/79241137a89c29d23d3e528ab52163f2aa2e6911 requires https://github.com/Agoric/agoric-sdk/pull/6757 to work

Wallet bridge

---

src/components/CollateralChoice.tsx
src/components/NewVault.tsx
src/service/vaults.ts
src/store/app.ts
src/store/vaults.ts
src/utils/displayFunctions.ts

refs https://github.com/Agoric/dapp-inter/issues/11

Open vault

---

src/App.tsx
src/config.ts
src/views/Root.tsx

fixes https://github.com/Agoric/dapp-inter/issues/35

feat: use hashrouter to support ipfs

---

src/service/vaults.ts
src/store/vaults.ts
src/utils/displayFunctions.ts

refs https://github.com/Agoric/dapp-inter/issues/2

feat: use vbank branded pricequotes

---

src/components/AmountInput.tsx
src/components/CollateralChoice.tsx
src/components/ConfigureNewVault.tsx
src/components/CreateVault.tsx
src/components/MainContentCard.tsx
src/components/MainContentWrapper.tsx
src/components/NetworkDropdown.tsx
src/components/NewVaultOfferSummary.tsx
src/views/Root.tsx
src/views/Vaults.tsx

feat: vault creation layout and styles

---

.eslintrc
src/components/AmountInput.tsx
src/components/CollateralChoice.tsx
src/components/ConfigureNewVault.tsx
src/components/CreateVault.tsx
src/components/NewVaultOfferSummary.tsx
src/components/RatioPercentInput.tsx
src/components/StyledInput.tsx
src/store/app.ts
src/store/createVault.ts
src/store/vaults.ts
src/utils/vaultMath.ts
src/views/Vaults.tsx

Vault Creation Flow

---

package.json
src/components/CollateralChoice.tsx
src/components/MainContentWrapper.tsx
src/components/ManageVaults.tsx
src/components/NewVaultOfferSummary.tsx
src/components/VaultSummary.tsx
src/service/vaults.ts
src/utils/displayFunctions.ts
src/utils/hooks.ts
src/views/Vaults.tsx
src/vite-env.d.ts
yarn.lock

Vault summary

---

package.json
src/components/AdjustVault.tsx
src/components/MainContentWrapper.tsx
src/components/ManageVaults.tsx
src/components/VaultSummary.tsx
src/store/vaults.ts
src/views/Vaults.tsx
src/vite-env.d.ts
yarn.lock

refs #15 
(The gif looks choppy, but you can see the animations for yourself in the ipfs deployments without a local chain running)

feat: add adjust vault view with transition

---

src/components/AdjustVault.tsx
src/components/AdjustVaultForm.tsx
src/components/AdjustVaultSummary.tsx
src/components/AmountInput.tsx
src/components/ConfigureNewVault.tsx
src/components/CreateVault.tsx
src/components/MainContentWrapper.tsx
src/components/ManageVaults.tsx
src/components/NewVaultOfferSummary.tsx
src/components/OfferSignerBridge.tsx
src/components/SmartWalletNotFoundToast.tsx
src/components/StyledDropdown.tsx
src/components/VaultCreationDialog.tsx
src/components/VaultSummary.tsx
src/config.ts
src/store/createVault.ts
src/store/vaults.ts
src/svg/error-warning.tsx
src/utils/displayFunctions.ts
src/utils/vaultMath.ts
src/views/Vaults.tsx

Adjust vault page layout

---

src/components/AdjustVaultForm.tsx
src/components/AdjustVaultSummary.tsx
src/components/VaultSummary.tsx
src/store/adjustVault.ts

Closed vault

---

src/components/AdjustVaultForm.tsx
src/components/AdjustVaultSummary.tsx
src/components/BaseDialog.tsx
src/components/CloseVaultDialog.tsx
src/components/VaultAdjustmentDialog.tsx
src/components/VaultCreationDialog.tsx
src/components/VaultSummary.tsx
src/service/vaults.ts
src/store/adjustVault.ts
src/store/createVault.ts
src/store/vaults.ts
src/utils/vaultMath.ts

feat: close vault dialog

---

README.md
src/config.ts
src/store/app.ts
src/views/Root.tsx

feat: network config env var to replace dropdown

---

.eslintignore
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/work_item.md
.github/workflows/deploy-inter.yml
.github/workflows/lint-test.yml
.prettierignore
README.md
package.json
patches/@agoric+smart-wallet+0.4.3-dev-8cbf697.0.patch
src/service/vaults.ts
src/store/vaults.ts
src/views/Vaults.tsx
yarn.lock

fixes: https://github.com/Agoric/dapp-inter/issues/68
Tested manually opening, adjusting, and closing a vault.
Blocked: requires https://github.com/Agoric/wallet-app/pull/59 and https://github.com/Agoric/agoric-sdk/pull/6996

feat: use new invitation spec

---

README.md
src/components/AdjustVault.tsx
src/components/ConfigureNewVault.tsx
src/components/OfferSignerBridge.tsx
src/components/SmartWalletNotFoundToast.tsx
src/service/wallet.ts
src/service/wallet.tsx
src/store/createVault.ts
src/utils/vaultMath.ts
test/utils/vaultMath.test.ts

fixes #77 
fixes #76 
fixes #74 
fixes #73
fixes #81

Fix Some Issues from VFT

---

README.md

Much of my changes overlapped with #86 so I rebased and applied my changes on top. Once that's merged I can update and undraft this one.
The resulting PR just adds requirements from agoric-sdk and cosmic-swingset (which are linked) and steps to verify the tools work, which ensure the scripts run successfully.

docs: clarify requirements and cli tools with tests

---

src/components/AdjustVaultForm.tsx
src/components/AdjustVaultSummary.tsx
src/components/ConfigureNewVault.tsx
src/components/NewVault.tsx
src/components/NewVaultOfferSummary.tsx
src/service/vaults.ts
src/store/adjustVault.ts
src/store/createVault.ts
src/utils/vaultMath.ts
test/utils/vaultMath.test.ts

feat: eliminate use of borrow term

---

src/store/adjustVault.ts

fix: show error when withdrawing more than locked

---

src/components/AdjustVaultForm.tsx
src/components/ConfigureNewVault.tsx
src/components/NewVaultOfferSummary.tsx
src/service/vaults.ts
src/store/adjustVault.ts
src/store/createVault.ts
src/store/vaults.ts
src/utils/vaultMath.ts
test/utils/vaultMath.test.ts

refs https://github.com/Agoric/agoric-sdk/issues/7099

chore: rename loanFee to mintFee

---

src/App.tsx
src/components/ActionsDialog.tsx
src/components/CloseVaultDialog.tsx
src/components/DisclaimerDialog.tsx
src/components/VaultAdjustmentDialog.tsx
src/components/VaultCreationDialog.tsx
src/config.ts
src/service/wallet.ts
src/store/app.ts

feat: legal disclaimer

---

src/components/AdjustVaultSummary.tsx
src/components/CollateralChoice.tsx
src/components/CreateVault.tsx
src/components/DisclaimerDialog.tsx
src/components/MainContentWrapper.tsx
src/components/ManageVaults.tsx
src/components/NewVaultOfferSummary.tsx
src/components/VaultSummary.tsx
src/service/vaults.ts
src/store/app.ts
src/store/createVault.ts

fixes https://github.com/Agoric/dapp-inter/issues/108
fixes https://github.com/Agoric/dapp-inter/issues/103
fixes https://github.com/Agoric/dapp-inter/issues/114
fixes https://github.com/Agoric/dapp-inter/issues/97
fixes https://github.com/Agoric/dapp-inter/issues/85 - Screenshots below...

Assorted fixes and improvements

---

src/components/AdjustVaultForm.tsx
src/components/AdjustVaultSummary.tsx

feat: adjust vault view improvements

---

index.html

feat: change page title

---

src/components/NewVaultOfferSummary.tsx

feat: enforce and warn about vault limit

---

src/components/CollateralChoice.tsx
src/components/ConnectWalletButton.tsx
src/components/ManageVaults.tsx
src/components/VaultSummary.tsx
src/service/vaults.ts
src/service/wallet.ts
src/store/app.ts
src/store/vaults.ts

fixes #82 
- Automatically try to connect wallet on load if user has connected before (stored in local storage).
- Default to "manage vaults" view if user has created a vault before (stored in local storage).
- Added loading animations to smoothen the "manage vaults" view.

Default to manage vaults view if user has created vault

---

src/components/AdjustVault.tsx
src/components/AdjustVaultForm.tsx
src/components/AdjustVaultInstructions.tsx
src/components/ManageVaults.tsx
src/components/VaultSummary.tsx
src/store/adjustVault.ts
src/utils/vaultMath.ts

fixes https://github.com/Agoric/dapp-inter/issues/106
fixes https://github.com/Agoric/dapp-inter/issues/83

Adjust Vault view enhancements

---

src/App.tsx
src/components/ActionsDialog.tsx
src/components/AppVersionDialog.tsx
src/service/vaults.ts
src/store/app.ts
src/store/vaults.ts
src/utils/ipfs.ts

fixes https://github.com/Agoric/dapp-inter/issues/127

feat: present dialog if newer app version available

---

src/components/AdjustVaultInstructions.tsx
src/service/wallet.ts

refs https://github.com/Agoric/agoric-sdk/issues/6552

feat: auto-dismiss no smart wallet toast

---

src/components/ActionsDialog.tsx
src/components/AdjustVault.tsx
src/components/AdjustVaultForm.tsx
src/components/AdjustVaultInstructions.tsx
src/components/AdjustVaultSummary.tsx
src/components/AmountInput.tsx
src/components/AssetTransferButton.tsx
src/components/CollateralChoice.tsx
src/components/ConfigureNewVault.tsx
src/components/ConnectWalletButton.tsx
src/components/CreateVault.tsx
src/components/DisclaimerDialog.tsx
src/components/MainContentWrapper.tsx
src/components/ManageVaults.tsx
src/components/NewVaultOfferSummary.tsx
src/components/StyledDropdown.tsx
src/components/StyledInput.tsx
src/components/VaultSummary.tsx
src/styles/base.css
src/styles/components.css
src/styles/globals.css
src/styles/utilities.css
src/views/Root.tsx
src/views/Vaults.tsx
tailwind.config.cjs

fixes https://github.com/Agoric/dapp-inter/issues/46
- Cleaned up the theme variables, removing bespoke styles (`[]` in `className`s) where possible.
- Used correct format for theme colors
- Changed some values that were close enough to barely be noticeable so they could reuse the same colors/shadows etc.
- Created some custom classes for buttons and stuff
The only `[]` remaining in the `className`s  as far as I can tell are one-offs, or have to do with spacing/layout.

Consolidate styles

---

package.json
src/App.tsx
src/rpc/index.ts
src/rpc/src/batchQuery.ts
src/rpc/src/chainStorageWatcher.ts
src/rpc/src/types.ts
src/rpc/test/chainStorageWatcher.test.ts
src/service/vaults.ts
src/service/vbank.ts
src/store/app.ts
src/utils/rpc.ts
src/views/Vaults.tsx
test/utils/vaultMath.test.ts
vitest.config.ts
yarn.lock

refs https://github.com/Agoric/agoric-sdk/issues/6870
This is in its own directory so that it's more portable. It will be copy-pasted into other dapps, but eventually live in a reusable package.
Tested manually after rewiring dapp to use the client, as well as unit tests. NOTE - The wallet connection component in agoric-sdk doesn't use this lib yet, so if you connect your wallet then you'll see a lot of unnecessary rpc requests still.

feat: batch chain storage query library

---

patches/@agoric+web-components+0.6.4-dev-933b31c.0.patch

refs https://github.com/Agoric/dapp-inter/issues/151

fix: dont hang on empty wallet data

---

src/components/ConfigureNewVault.tsx
src/components/ManageVaults.tsx
src/components/VaultSummary.tsx
src/service/vaults.ts
src/store/adjustVault.ts
src/store/createVault.ts
src/store/vaults.ts
src/utils/vaultMath.ts

fixes https://github.com/Agoric/dapp-inter/issues/159
Functionality affected by https://github.com/Agoric/agoric-sdk/issues/8041 but not a blocker

fix: use lockedQuote for auction price

---

src/components/AdjustVaultForm.tsx
src/components/ConfigureNewVault.tsx
src/components/VaultSummary.tsx
src/components/leap-elements/LiquidityModal.tsx

fixes https://github.com/Agoric/dapp-inter/issues/239

feat: add withdraw button to closed vaults

---

package.json
yarn.lock

Things I did to verify this:
`yarn dev` and navigate to http://localhost:5173 to verify that the UI can load now.

fix: run `yarn upgrade ses`

---

package.json
patches/vitest+0.32.0.patch
src/components/ProvisionSmartWalletNoticeDialog.tsx
src/store/app.ts
src/store/vaults.ts
src/utils/swingsetParams.ts
src/vite-env.d.ts
yarn.lock

Reverts Agoric/dapp-inter#240
Refs https://github.com/Agoric/dapp-inter/issues/252

Revert "use Telescope-based cosmic-proto"

---

src/components/AdjustVaultForm.tsx
src/components/AdjustVaultSummary.tsx
src/components/NewVaultOfferSummary.tsx

fixes https://github.com/Agoric/dapp-inter/issues/247
fixes https://github.com/Agoric/dapp-inter/issues/248

Minting fee

---

src/components/ConfigureNewVault.tsx
src/store/app.ts
src/store/vaults.ts
src/views/Root.tsx
src/views/Vaults.tsx

fixes https://github.com/Agoric/dapp-inter/issues/277
fixes https://github.com/Agoric/dapp-inter/issues/175
fixes https://github.com/Agoric/dapp-inter/issues/170
fixes https://github.com/Agoric/dapp-inter/issues/166

Vaults UI Enhancements

---

.github/workflows/liquidation-reconstitution.yml
test/e2e/docker-compose-reconstitution.yml
test/e2e/specs/liquidation-reconstitution.spec.js

The PR adds:
- Test cases for vault's undergoing reconstitution scanerios. 
- CI implementation for running these test cases in a separate Github Action runner.

reconstitution test cases

---

.github/workflows/reusable-workflow.yml
.github/workflows/vaults.yml
test/e2e/docker-compose-base.yml
test/e2e/specs/test.spec.js

adds a manual workflow trigger to run the vaults test
also add the ability to pass a custom mnemonic phrase to skip wallet setup

ci: manual trigger to run emerynet tests

---

test/e2e/specs/liquidation-reconstitution.spec.js
test/e2e/specs/liquidation.spec.js
test/e2e/support.js

- Adds waits when verifying auction values to ensure accuracy.
- Segregates tests related to claiming collateral into three separate tests for each vault. This approach has proven to be more reliable, as looping introduces an element of flakiness due to the rapid processing.

chores in cleanup tests for liquidation 

---

src/components/MainContentWrapper.tsx
src/store/app.ts
src/utils/hooks.ts
src/utils/rpc.ts

fixes https://github.com/Agoric/dapp-inter/issues/311

fix: use subquery to count all active vaults

---

.github/actions/notify-status/action.yml
.github/workflows/reusable-workflow.yml
.github/workflows/vaults.yml

The PR adds CI implementation for sending alerts on Slack when E2E tests fail.

feat: alert slack if e2e tests fail

---

.github/workflows/liquidation-reconstitution.yml
.github/workflows/liquidation.yml
.github/workflows/reusable-workflow.yml
Dockerfile
test/e2e/docker-compose-base.yml

ci: add dynamic tagging to Docker setup

---

test/e2e/specs/liquidation-reconstitution.spec.js
test/e2e/specs/liquidation.spec.js

test: fix flaky liquidation tests

---

.github/workflows/liquidation-reconstitution.yml
.github/workflows/liquidation.yml

fix: set base image tag to latest for workflows trigger

---

.github/workflows/reusable-workflow.yml

- updates artifact url to observed value

chore(test): update artifact url

---

test/e2e/specs/liquidation-reconstitution.spec.js

enable disabled tests for a3p testing

---

test/e2e/specs/liquidation.spec.js
test/e2e/support.js
test/e2e/test.utils.js

- Enables tests for claiming collateral with A3P. 
- Automates the verification of ATOM balance after claiming collateral. 
- Automates the process of verifying bids after vaults liquidate.

automate ATOM balance verification after transactions

---

test/e2e/specs/liquidation-reconstitution.spec.js
test/e2e/specs/liquidation.spec.js
test/e2e/support.js
test/e2e/test.utils.js

The PR:
- Updates the command to fetch balance to be generic. 
- Updates and adds additional tests to verify ATOM and IST balance.

generic command to fetch balances and update tests

---

test/e2e/specs/liquidation-reconstitution.spec.js
test/e2e/specs/liquidation.spec.js
test/e2e/support.js
test/e2e/test.utils.js

Tests are added to verify the value for shortfall balance in liquidation tests.

verify shortfall balance and debt burned

---

test/e2e/specs/liquidation-reconstitution.spec.js
test/e2e/specs/liquidation.spec.js
test/e2e/support.js
test/e2e/test.utils.js

Create a new wallet designed for vault creation

---

.github/workflows/liquidation-reconstitution.yml
.github/workflows/liquidation.yml
.github/workflows/reusable-workflow.yml
README.md

This PR makes updates in docs and removes not used input variables in CI due to recent changes in #383

Update docs and CI workflows of e2e tests
