Agoric/dapp-inter

- src/components/CollateralChoice.tsx
- src/components/ManageVaults.tsx
- src/components/NewVault.tsx
- src/components/VaultSummary.tsx
- src/service/vaults.ts
- src/store/vaults.ts
- src/views/Vaults.tsx
refs https://github.com/Agoric/dapp-inter/issues/13
refs https://github.com/Agoric/dapp-inter/issues/12
The loading states for the  "Manage Vaults" view could be handled a little smoother. Right now the vaults just pop up as each one loads individually, async. This can be improved on further when we can load *only* the user's vaults (https://github.com/Agoric/agoric-sdk/issues/6665), since a lot of this code will need to be rewritten then.
For now this just establishes some basic vault loading/rendering:
> Show vaults

- patches/@agoric+smart-wallet+0.4.3-dev-1adb7a2.0.patch
Using patch-package still just to unblock and because I'm not sure if we want the version used by the smart wallet to be null-friendly.
> fix: restore import context patch

- .github/workflows/deploy-inter.yml
I found the long urls in the IPFS comment distracting.
**Before**
**After**
> build: cleaner ipfs comment

- src/service/vaults.ts
- src/store/createVault.ts
- src/utils/vaultMath.ts
- test/utils/vaultMath.test.ts
- Use full debt limit now that we have: https://github.com/Agoric/agoric-sdk/pull/6984
- Fix rounding error for "max" button in vault creation and added test.
> fix: use max debt limit

- src/components/NetworkDropdown.tsx
- src/config.ts
Allows a `network=ollinet` or default for network selection
> feat: allow queryparam netselect

- src/service/wallet.ts
Vaults weren't loading because we changed the wallet to publish an array of entries rather than a record for its public subscribers [#Agoric/agoric-sdk/7139](https://github.com/Agoric/agoric-sdk/pull/7139). This updates the UI to view parse them correctly.
> fix: convert entries from wallet

- src/service/vaults.ts
required for https://github.com/Agoric/agoric-sdk/pull/7150
Support both before and after schemes. We can drop support for the old scheme when it's known not to be served.
> feat: support new managers vstorage path

- src/App.tsx
- src/components/AdjustVault.tsx
- src/components/AdjustVaultForm.tsx
- src/components/ConfigureNewVault.tsx
- src/components/VaultSummary.tsx
- src/service/vaults.ts
- src/store/adjustVault.ts
- src/store/app.ts
- src/store/createVault.ts
- src/utils/date.ts
- src/utils/hooks.ts
- src/utils/vaultMath.ts
- test/utils/vaultMath.test.ts
fixes #100 
fixes #101 
Makes the "max" button use the lowest of next liquidation/current quote price when creating and adjusting vaults, and enforces collat. ratio based on lowest price when creating a vault.
Shows next liquidation price during price lock period in creation and adjustment views:
Tested manually throughout price lock periods on a local chain and added unit tests for new cases
> feat: account for locked price in creation and adjustment

- src/rpc/src/batchQuery.ts
- src/rpc/test/chainStorageWatcher.test.ts
@gibson042 Pointed out that the ordering of responses is not guaranteed in batch queries, we should rely on the id field instead
> fix: rely on ids not ordering for batch query

- src/components/ConnectWalletButton.tsx
- Don't let the user click connect until `chainStorageWatcher` is initialized (which happens after network config is fetched). That's because `makeAgoricWalletConnection` requires it.
- Fix the loading spinner animation. We changed the css variables and that broke the styles there.
> fix: connect wallet button bugs

- package.json
- src/App.tsx
- src/components/CollateralChoice.tsx
- yarn.lock
fixes https://github.com/Agoric/dapp-inter/issues/196
Also updates the `ui-kit` deps to the latest.
> fix: dont capitalize collateral choice

- src/config.ts
- src/views/Root.tsx
Closes: #148 #157
Cross dapp connection needed to be improved
Added two external links to navigate the user to `PSM` and `Analytics` pages that use the below links respectively
* https://psm.inter.trade/
* https://info.inter.trade/
> feat: navigate to 'PSM' and 'Analytics' from the navigation bar

- package.json
- src/App.tsx
- src/components/ChainConnectionErrorDialog.tsx
- src/components/Combobox.tsx
- src/components/NetworkDropdown.tsx
- src/components/NodeSelectorDialog.tsx
- src/store/app.ts
- src/utils/rpc.ts
refs https://github.com/Agoric/agoric-sdk/issues/8505
refs https://github.com/Agoric/dapp-inter/issues/211
This adds a "connection settings" button to the chain connection error dialog which allows you to select API and RPC nodes. It saves your selections to local storage, which take priority over whichever nodes are loaded from the network config.
It doesn't provide an entrypoint to the node selector outside of the error dialog, that can be added in a future PR. Also, if you change networks (dev/testnet only, as mainnet doesn't have the network dropdown), it just deletes the saved nodes, instead of saving a map of saved nodes for every network.
(Animations look choppy in the gif due to compression, but you can try it in the live demo in the comments yourself)
> feat: allow node selection after connection error

- src/components/Combobox.tsx
- src/components/NodeSelectorDialog.tsx
- src/components/SettingsButton.tsx
- src/views/Root.tsx
fixes https://github.com/Agoric/dapp-inter/issues/211
Also improved a11y of node selector dialog by making it work with keyboard users. Before, if you wanted to add a custom node, you had to type it then click out of the input box to select it. If you pressed tab or enter, it would revert the custom input.
> Node selector button

- src/components/CollateralChoice.tsx
- src/components/CreateVault.tsx
- src/components/ProvisionSmartWalletNoticeDialog.tsx
- src/store/app.ts
- src/utils/displayFunctions.ts
fixes https://github.com/Agoric/dapp-inter/issues/236
Fixes the vault cards to 256x248px, uses a new `displayAbbreviatedAmount` utility that shows at most 5 significant figures to prevent overflow, also shows 4 skeleton loading collateral choices by default to decrease layout thrashing when loading.
> feat: make collateral cards same size

- src/components/MainContentWrapper.tsx
- src/components/ProvisionSmartWalletNoticeDialog.tsx
- src/components/leap-elements/LiquidityModal.tsx
- yarn.lock
fixes https://github.com/Agoric/dapp-inter/issues/244
> feat: deposit ist from provision dialog

- src/components/ConnectWalletButton.tsx
Issue:
I've encountered an error after installing a new Keplr extension and visiting the dapp-inter URL. When attempting to connect with the wallet, I receive the following error:
This happens because when I imported or created my wallet, I didn't select the Agoric Chain. Also, there weren't any options available to select any testing chains:
I noticed that new users may have trouble connecting to the wallet. Typically, we can connect without any problems, but it seems that if we're already connected to the testing chains, it's easier. For example, when I was using the `offerup` dapp initially and then switched to `dapp-inter`, connecting my wallet was smooth because I was already connected to the Agoric chain during my work with `offerup` dapp.
What I've observed is that new users might …
> chore: suggest connection with chain before connecting with wallet

- .dockerignore
- .github/workflows/e2e_tests.yml
- .gitignore
- Dockerfile
- package.json
- test/e2e/docker-compose.yml
- test/e2e/nginx.conf
- yarn.lock
This PR adds the github workflow for the e2e tests.
The workflow consists of running a docker compose file that contains the following services:
- `synpress`: the main container that runs the tests
- `display`: this service is required by the `synpress` container in order to create a display for headed browser
- `ngrok`: this service creates an external URL that can be used to VNC into the `display` service
- `video`: this service creates a screen recording of the `display` service that can be later used viewed
- `agd`: this service creates a local agoric chain that is used by the `synpress` container
> test: CI/CD workflow for e2e tests

- Dockerfile
- test/e2e/docker-compose.yml
The PR updates the base image from `synthetixio/docker-e2e` to `ghcr.io/agoric/agoric-sdk:latest` in order to support Agoric shell commands within the CI)environment. It includes necessary modifications to ensure the smooth functioning of the CI process with the new base image.
> chore: update ci for dapp-inter to run shell commands

- package.json
- src/config.ts
- test/e2e/docker-compose.yml
- test/e2e/specs/test.spec.js
The PR:
- Replaces `image: ghcr.io/agoric/agoric-3-proposals:main` with `image: ghcr.io/agoric/agoric-3-proposals:latest`
- Modifies the test cases for the use with `image: ghcr.io/agoric/agoric-3-proposals:latest`
> chore: adjusting e2e test cases with a3p:latest

- .github/workflows/e2e_tests.yml
- .github/workflows/reusable-workflow.yml
- .github/workflows/vaults.yml
- package.json
- test/e2e/docker-compose-base.yml
- test/e2e/docker-compose-vaults.yml
- Split the docker-compose file into shared(`docker-compose-base.yml`) and specific(`docker-compose-vaults.yml`) configurations.
- Added a reusable workflow for end-to-end (E2E) tests.
While working on Liquidation tests in PR #268, I noticed that the CI process takes too long because we were running both Vaults and Liquidation test cases in a single GitHub Actions runner. To optimize our CI workflow, this PR enables parallel GitHub Action runners for running Vaults and Liquidation(when #268 is merged) E2E tests separately. This can save us time and simplify the management of our tests and CI workflows.
I've already implemented these changes in PR #268, but I want to keep that PR focused and prevent it from becoming too large. Once this PR is merged, I can rebase PR #268 accordingly.
> ci: split docker compose and add reusable E2E workflow

- Dockerfile
- test/e2e/support.js
- Simplifies the cypress custom command for adding keys from the shell. 
- Remove installing `expect` package in the `Dockerfile`. This package was previously used with `agd keys add` command.
> refactor: simplify cypress command for adding keys from shell

- test/e2e/specs/liquidation.spec.js
- test/e2e/support.js
- test/e2e/test.utils.js
The PR adds tests to ensure vaults are in a `liquidating` state and verifies the auction data. 
It also adds tests for verifying if a vault has reached a `liquidated` state but I'm currently deferring the execution of these tests in CI after updating the a3p Docker container, as I've noticed a discrepancy in behavior.
> test: liquidate vaults and viewing auction data

- .github/workflows/reusable-workflow.yml
- .github/workflows/vaults.yml
- test/e2e/.eslintrc.cjs
- test/e2e/docker-compose-base.yml
- test/e2e/docker-compose-vaults.yml
- test/e2e/specs/test.spec.js
- test/e2e/synpress.config.cjs
- test/e2e/test.utils.js
This PR does the following:
- It adjusts the previously written tests to work for both local network and emerynet. these updates include
- changing the order of test to make the transactions cyclic. i.e. the amount put into the vault is returned in the end
- update the wallet creation flow to use previously created wallet on local but to create a brand new wallet on emerynet
- it adds a scheduled run of the e2e_tests github action to run once everyday on emerynet 
**Note:** the behaviour of provisioning ATOM and IST from https://emerynet.faucet.agoric.net seems to be unreliable and flaky, but at the moment I am not aware of any other way to get these tokens in a new account
> ci: add daliy scheduled run for emerynet testing

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
Due to the lengthy execution time of 20 to 25 minutes for liquidation tests on the local chain, the PR excludes these tests from PR executions. Instead, we will schedule regular runs of these tests.
> ci: add scheduled runs of liquidation tests

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/support.js
- test/e2e/test.utils.js
- Setup manager params from econ-gov.
- Setup auctioneer params from econ-gov. 
- Changes in setting up wallet test case for dapp-inter. 
- Exporting `AGORIC_NET` when running shell commands. This will assist when setting up these tests with emerynet.
> tests: add tests for setting up governance params

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/test.utils.js
- Implements a test to reset the ATOM price to `12.34` in Emerynet, ensuring the resumption of normal operations.
- Adds a test to remove the `150 IST` bid in the liquidation happy path tests, to prevent any impact on subsequent test runs.
> cleanup tests for emerynet 

- .dockerignore
- .eslintignore
- .github/workflows/reusable-workflow.yml
- .gitignore
- .prettierignore
This pull request enables the uploading of end-to-end tests to Google Cloud Platform (GCP).
I tested this workflow in this [GitHub Action run](https://github.com/Agoric/dapp-inter/actions/runs/9352479080/job/25740739716?pr=297) by making a dummy commit.
> ci: artifacts setup for dapp-inter

- src/service/vaults.ts
fixes https://github.com/Agoric/dapp-inter/issues/299
> feat: trivially change price feed error message

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
- test/e2e/specs/liquidation.spec.js
While running emerynet tests in CI for liquidation workflows, the environment variables were not picked up in the code. Their values were `undefined`.
After inspecting, I found that we need to pass the secrets to the reusable workflow from where it's being called. You can refer to this [GitHub documentation on using inputs and secrets in a reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow) for more details.
In our CI setup, we have a file named `reusable.workflow.yml`, which is called in both `liquidation.yml` and `liquidation-reconstitution.yml`. In this PR, I am passing the secrets from these workflows to the reusable workflow.
> passing env variables to the reusable workflow

- src/components/AdjustVaultSummary.tsx
- src/components/NewVaultOfferSummary.tsx
See #223 
Added a small fix since Collateralization Ratio always appeared to be "changed". Here's the before:
> feat: show liquidation price in vault summary

- test/e2e/docker-compose-liquidation.yml
- test/e2e/docker-compose-reconstitution.yml
The PR disables running the nginx server when we execute emerynet tests for liquidations.
> chore: disable nginx with emerynet

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/test.utils.js
- Makes sure we use different timeouts for liquidation based on network. 
- Modifications in tests to ensure we don't wait much for desired results in case of failure.
> chore: use different timeouts based on network

- test/e2e/support.js
- test/e2e/test.utils.js
Sometimes the command related to creating vaults timeouts with emerynet tests for liquidation. In this PR, I address that issue by using different timeouts for local and emerynet tests.
> chore: increase command timeout for emerynet

- test/e2e/specs/test.spec.js
- test/e2e/support.js
- test/e2e/test.utils.js
This PR makes the following updates to CI tests to reduce flakiness:
- first it updates the flow to get the chain address. we were originally using the wallet dapp for this but a good solution instead is to use the address of the original 'Agoric' chain, since it will be the same for emerynet
- second, it updates the flow for provisoin tokens using the emerynet faucet. previously we were doing it through the emerynet faucet ui, but now we are performing it thorugh direct API request, which allows us to retry on failure
> test: updated tests to reduce flakiness for wallet setup

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/test.utils.js
- Segregates tests related to closing vaults and canceling bids into a separate context. 
- Removes 3-second wait when verifying auction data. Adding this wait did not bring any stability in the tests. 
- Update the tests related to claiming collateral. Use a different selector and add new timeout values based on the consideration for a busy network. 
- When canceling the bids that are not accepted, sometimes there is flaky behavior when switching to a new wallet. I've been inspecting this but not sure why that tends to happen. Switching the wallet in a separate test case solves the problem.
> reduce flakiness with cleanup tests

- .github/workflows/deploy-poller.yml
- .github/workflows/upstream-sync.yml
Closes https://github.com/Agoric/product-tasks/issues/107
Closes https://github.com/Agoric/product-tasks/issues/111
This change introduces two workflows that work in tandem to facilitate automated deploy of `dapp-inter`. Steps are as follows:
1. `upstream-sync` will monitor, at a five minute cadence, for new changes on the upstream branch. If any changes have been detected, we'll update our tracking branch to mirror the new `main` branch of the upstream branch.
2. When it's time to vote on a new deploy, we'll take the commit hash of the candidate and save it to `ReferenceUI` in.
3. `deploy-poller` will monitor, at a five minute cadence, for any updates to the `ReferenceUI` value in vstorage. If a change is detected, it will proceed with taking the `ReferenceUI` commit and pushing it to …
> Add GH workflows to facilitate autonomous deploy to CF

- .github/workflows/deploy-poller.yml
With this change, we will now be able to deploy any commit from any repository, as long as that commit and repository are publicly accessible and on GitHub. We expect the value of `ReferencedUI` to be a GitHub link pointing to a commit. For example: `https://github.com/Agoric/dapp-inter/commit/67b782c8def0bd8a7bf3ba8016aac77e451970fe`.
When receiving a link in this format, the workflow will split the link into the url needed to clone the branch and the commit to checkout. We will then push the commit to the deploy branch.
The workflow also has input, so that testing and manual deploy is easy and configurable
> Create deploy branch from any commit to deploy to CloudFlare pages

- .github/workflows/deploy-poller.yml
We can have the `DEPLOYED_HASH` value stored in the deploy branch. We already make a commit on top of the target commit, so it's a simple addition.
Passing actions run: https://github.com/Agoric/dapp-inter/actions/runs/10115904779
> Commit DEPLOYED_HASH to deploy branch instead of main

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
- .github/workflows/reusable-workflow.yml
- .github/workflows/vaults.yml
Refs: https://github.com/Agoric/dapp-econ-gov/issues/111
Fixes some flakes in e2e testing.
- Firstly used docker compose instead of docker-compose (which is not being recognized by github actions)
- Secondly removed some unnecessary steps to give some space to the github runner, otherwise the job was failing due to space limit being reached
> ci: change docker-compose to docker compose

- test/e2e/specs/test.spec.js
Fixes: #340 
The "Keep using old version" button appears depending on the current version of dapp being used. so it might appear or not depending on the version being used.
Since this exists/does not exist case can introduce unexpected failures in the e2e tests, the line of code referencing it has been made conditional depending on whether the button is found or not.
> test: added conditional check for 'Keep using old version' button

- .github/workflows/upstream-sync.yml
When syncing, it's possible that the workflow folder has also changed. Unfortunately, the default Actions worker doesn't have the correct permissions to check in modified workflow files. To workaround this, we always ensure that when we push changes, we remove all files in the `.github/workflows` directory that don't exist on the remote.
> Fix workflow permissions for upstream sync workflow

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
The PR introduces the capability to trigger liquidation end-to-end tests using labels. Previously, for liquidation testing, we had to either test things locally or wait for our PR to be merged into the main branch before triggering the liquidation workflows. 
In this PR, we bring these capabilities:
- Adding the `liquidation-testing label` to a PR will trigger all liquidation tests.
- Adding the `liquidation-reconstitution-testing` label to a PR will trigger all liquidation reconstitution tests.
- Adding the `emerynet` label will trigger the Liquidation and Liquidation Reconstitution tests against the Emerynet network, provided that the `liquidation-testing` or `liquidation-reconstitution` labels have also been added to the PR.
> ci: label triggered liquidation testing

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
- test/e2e/docker-compose-liquidation.yml
- test/e2e/docker-compose-reconstitution.yml
When liquidation tests are triggered, the Agoric local chain is also started. However, we don’t need the local chain when the tests are triggered with Emerynet. This PR resolves this issue by utilizing Docker Compose profiles. It reuses the profiles already used in the E2E tests for vaults.
> ci: use docker compose profiles in liquidation tests

- test/e2e/specs/test.spec.js
- test/e2e/support.js
While running liquidation tests on Emerynet, I encountered a failure in the test related to connecting with the wallet. Interestingly, this issue had already been resolved by @frazarshad in PR #339 for the vault end-to-end tests. The process for connecting a wallet when using a local chain or Emerynet is the same for both vault and liquidation tests.
In this pull request, I've applied the changes from PR #339 to the custom command used for wallet connection. I also updated the vault tests to use this custom command when connecting to the wallet. This ensures consistency across both vault and liquidation tests, making it easier to identify and fix any future errors.
> test: fix connect wallet test case

- test/e2e/support.js
Currently, Cypress primarily displays test failures in the Cypress Command Console within the browser. While this works fine locally, allowing you to instantly see the reasons for test failures, it's not feasible in a CI environment. To address this, the PR introduces functionality that outputs the test failure reasons directly to the terminal (stdout) as soon as a test fails.
Here’s an example workflow where I successfully retrieved the reasons for some test failures:
https://github.com/Agoric/dapp-inter/actions/runs/10489730491/job/29055008052
> test: show logs after failing test

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
- .github/workflows/reusable-workflow.yml
- .github/workflows/vaults.yml
- README.md
- test/e2e/docker-compose-base.yml
- Adding support to test the a3p chain with custom tags.
- Removes the input of governance wallets in ci.
> ci: input tags for a3p

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
Scheduled liquidation tests are typically run with the a3p chain, but due to recent changes, they were being executed against emerynet. This pull request resolves that issue.
> fix: run liquidation scheduled e2e tests with a3p

- test/e2e/specs/test.spec.js
Usually, when we create a new wallet on `emerynet`, we manually obtain testnet tokens from the faucet, which gives us enough ATOMs to perform e2e tests of vaults. However, this isn't the case with `xnet`. In this PR, for `xnet`, we've opted to use a custom wallet that comes with a sufficient amount of ATOMs to ensure the e2e tests of vaults function correctly.
> changes related to xnet in e2e tests for vaults

- .github/workflows/upstream-sync.yml
After we included the change to always push a commit removing changes to the workflow file, this caused the sync to always push a change to the deploy branch, even when there were none. To fix this, we'll check the diff between the remote and origin before attempting to sync.
Action run showing skipping of steps if there are no detected changes
> Check if there are any changes on remote before syncing

- README.md
The PR improves the documentation by removing redundant information about running end-to-end tests locally and adds better structure for executing these tests.
> docs: update docs for running e2e tests with local chain

- .github/workflows/vaults.yml
- test/e2e/support.js
- test/e2e/test.utils.js
Updated test to poll for transaction completion
> Faucet Polling in E2E Tests

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
- .github/workflows/reusable-workflow.yml
- .github/workflows/vaults.yml
- test/e2e/docker-compose-base.yml
This PR introduces the ability to input a custom image name for E2E testing.
- Previously, we used the image `ghcr.io/agoric/agoric-3-proposals` for E2E testing.
- We could specify the `tag` for this image during testing in CI via an input.
- Recently, images like `ghcr.io/agoric/agoric-sdk:a3p-use-upgrade-next-20240911203722-bc66a5` started being used for E2E testing, in `u17`.
- To test this image in CI, we manually hardcoded the image name in the `docker-compose` file (as done in #365). This was not ideal.
> ci: image parameterization via env variables

- .github/workflows/liquidation-reconstitution.yml
- .github/workflows/liquidation.yml
- .github/workflows/vaults.yml
- test/e2e/specs/test.spec.js
tests are flaky because the transactions that occur in these tests can fail due to "account sequence mismatch" error. to avoid this error, we simply need to retry this transaction. This is what this PR attempts to do.
It also updates the scheduled time of these tests to avoid running with tests from other repositories. thereby reducing the chance of a "account sequence mismatch" error
> test: retry transactions to avoid account sequence mismatch error

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/support.js
- test/e2e/test.utils.js
closes [#216](https://github.com/Agoric/agoric-private/issues/216)
This PR includes the following updates:
- Adds a custom command to get data from VStorage.
- Uses this command to get Auction data.
The old auction instance overwrites new auction instance values, so for A3P testing, I now get auction data from VStorage instead of using the `agops inter auction status` command. We’ll still use the `agops` command for testnets, but for A3P tests, VStorage will be the source. After getting the data, the test checks for the right auction values. If found, the test passes.
> test: fix and structure tests related to auction

- .github/workflows/vaults.yml
Currently, Vault tests are triggered when someone edits the PR description or makes any changes linked to the edited event in GitHub Actions. This causes the Vault CI workflow to restart even after it has already passed, which is unnecessary.
This PR fixes the issue by removing the edited event from the Vault workflow.
> dont trigger vault tests on `edited` event

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/test.utils.js
- Replicates changes from #373 for liquidation-reconstitution tests, to verify ATOM balance after relevant ATOM transactions. 
- Enables and adds some tests related to canceling of bids - catered for a3p.  
- Adjusting the waiting period before balance checks. Mainly reducing the value.
> Improvements in e2e tests

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/support.js
- test/e2e/test.utils.js
Sometimes when running liquidation end-to-end tests, certain tests fail due to auction-related issues. The problem occurs because the value received from the auction doesn't exactly match the expected value, with the difference usually being a small amount, often at the last decimal place.
This PR updates the custom command for getting auction values. It ensures that we compare the correct number of decimal places for more accurate results.
> Improvements when comparing decimal values 

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/support.js
The PR:
- Verifies `user1` and `bidder` balance before executing all tests. This is done to exit early in case the balances are not enough to carry out test operations. Previously, we had executed a major section of tests before realizing that we didn't possess enough balance to create a vault or make a bid. 
- Removes an A3P test for creating a vault which is no longer required. Previously, this test case was added to ensure `gov1` has enough `IST` to make bids. But this is no longer required because `gov1` already have enough balance to carry out bidding stuff. 
- Adding logs wherever we execute commands with `agops` and `agd`.
> Skip tests if not enough balance

- test/e2e/specs/liquidation-reconstitution.spec.js
This PR ensures that the expected value for shortfall balance comparisons is rounded to two decimal places, matching the format of the actual test output.
Currently, the comparison fails because the actual value `5.53` does not match the expected value `5.525`.
> chore: compare values upto 2 decimal places

- test/e2e/specs/liquidation-reconstitution.spec.js
- test/e2e/specs/liquidation.spec.js
- test/e2e/support.js
- test/e2e/test.utils.js
- Use absolute path for `agops` in CI. 
- Chores around bringing consistency in running e2e tests between a3p and testnets. 
- Wraps logs in a separate `then` callback. 
- Adds a retry mechanism for auction-specific test cases.
> fix e2e tests issues when running with emerynet

- src/utils/rpc.ts
Onfinality has changed the API URL. Right now both the old and new ones work so changing it pre-emptively on the inter dashboard. 
Will be re-deploying the production indexer today so the old one will stop working as soon as its done.
> chore: update subquery url
